apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: "https://github.com/steddyman/namespace-test.git" # Can point to either a Helm chart repo or a git repo.
    path: overlay/pdev/
    targetRevision: HEAD # Branch or Tag
    # path: base # This has no meaning for Helm charts pulled directly from a Helm repo instead of git.

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  # Sync policy
  syncPolicy:
    automated: {}
