apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  source:
    targetRevision: 1.16.2
    helm:
      values: |
        test: false
        global:
          istioNamespace: "istio-system"
